### PR TITLE
Intro to galaxy text file upload

### PR DESCRIPTION
**Pull request by tralynca**
[Intro_to_Galaxy_March_2024.txt](https://github.com/SANBI-SA/pathogen-genomics-march-2024/files/14465092/Intro_to_Galaxy_March_2024.txt)

### CODE REVIEW

**Comment by pvanheus** [comment]
Hi @tralynca 

If you're trying to put something in the Galaxy section of the course, put in in `modules/galaxy-introduction/_posts` folder and name the file as something ending `.md`. BTW the filename that is currently in that folder looks like it starts with a date: the main thing is just that these "dates" are used as ordering. E.g. your first file could be `2024-02-01-galaxy-intro.md` and the next one `2024-02-02-galaxy-next-steps.md` etc.

**Comment by pvanheus** [comment]
BTW @tralynca just in case you don't know - if you keep pushing commits to the branch (`tralynca-patch-1`) that you used to make this PR, it updates the PR.

**Comment by pvanheus** [comment]
This looks good. Just one thing - you still have `Intro_to_Galaxy_March_2024.txt` - do you need this? And if so, what is the file doing?

**Comment by tralynca** [comment]
I think that was a placeholder file that Perceval created.Is it the one named 2024_02_23-Galaxy.md?Cos I can’t find the one with the name below?On 03 Mar 2024, at 17:52, pvanheus ***@***.***> wrote:﻿
This looks good. Just one thing - you still have Intro_to_Galaxy_March_2024.txt - do you need this? And if so, what is the file doing?

**Comment by tralynca** [comment]
delete

**Comment by tralynca** [comment]
Oh I see it now under the PRsI thought that was deleted. On 03 Mar 2024, at 17:52, pvanheus ***@***.***> wrote:﻿
This looks good. Just one thing - you still have Intro_to_Galaxy_March_2024.txt - do you need this? And if so, what is the file doing?

**Comment by pvanheus** [comment]
You might want to do a `git rm Intro_to_Galaxy_March_2024.txt` and commit / push to get rid of that file.

**Pull request merged**
